Vagrant.configure("2") do |config|
  # PXE сервер
  config.vm.define "pxeserver" do |server|
    server.vm.box = "bento/ubuntu-22.04"
    server.vm.host_name = "pxeserver"
    server.vm.network "private_network", ip: "10.0.0.20", virtualbox__intnet: "pxenet"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      # Отключаем firewall
      sudo systemctl stop ufw
      sudo systemctl disable ufw
      
      # Устанавливаем dnsmasq
      sudo apt update
      sudo apt install -y dnsmasq apache2 wget
      
      # Настраиваем dnsmasq
      sudo bash -c 'cat > /etc/dnsmasq.d/pxe.conf' << EOF
interface=eth1
bind-interfaces
dhcp-range=eth1,10.0.0.100,10.0.0.120
dhcp-boot=pxelinux.0
dhcp-match=set:efi-x86_64,option:client-arch,7
dhcp-boot=tag:efi-x86_64,bootx64.efi
enable-tftp
tftp-root=/srv/tftp/amd64
EOF

      # Создаём каталоги для TFTP и скачиваем файлы PXE
      sudo mkdir -p /srv/tftp
      cd /srv/tftp
      sudo wget http://cdimage.ubuntu.com/ubuntu-server/daily-live/current/noble-netboot-amd64.tar.gz
      sudo tar -xzvf noble-netboot-amd64.tar.gz -C /srv/tftp
      
      # Перезапускаем dnsmasq
      sudo systemctl restart dnsmasq

      # Настраиваем Apache
      sudo mkdir -p /srv/images
      cd /srv/images
      sudo wget http://cdimage.ubuntu.com/ubuntu-server/daily-live/current/noble-live-server-amd64.iso

      # Конфигурация Apache для ks-server
      sudo bash -c 'cat > /etc/apache2/sites-available/ks-server.conf' << EOF
<VirtualHost 10.0.0.20:80>
    DocumentRoot /
    <Directory /srv/images>
        Options Indexes MultiViews
        AllowOverride All
        Require all granted
    </Directory>
    <Directory /srv/ks>
        Options Indexes MultiViews
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
EOF

      sudo mkdir -p /srv/ks
      sudo bash -c 'cat > /srv/ks/user-data' << EOF
#cloud-config
autoinstall:
  identity:
    hostname: linux
    username: otus
    password: $6$sJgo6Hg5zXBwkkI8$btrEoWAb5FxKhajagWR49XM4EAOfO/Dr5bMrLOkGe3KkMYdsh7T3MU5mYwY2TIMJpVKckAwnZFs2ltUJ1abOZ.
  keyboard:
    layout: us
  locale: en_US.UTF-8
  network:
    ethernets:
      enp0s3:
        dhcp4: true
      enp0s8:
        dhcp4: true
    version: 2
  ssh:
    allow-pw: true
  updates: security
  version: 1
EOF

      sudo touch /srv/ks/meta-data

      # Настройка PXE
      sudo bash -c 'cat > /srv/tftp/amd64/pxelinux.cfg/default' << EOF
DEFAULT install
LABEL install
KERNEL linux
INITRD initrd
APPEND root=/dev/ram0 ramdisk_size=3000000 ip=dhcp iso-url=http://10.0.0.20/srv/images/noble-live-server-amd64.iso autoinstall ds=nocloud-net;s=http://10.0.0.20/srv/ks/
EOF

      # Перезапуск служб
      sudo a2ensite ks-server.conf
      sudo systemctl restart apache2
      sudo systemctl restart dnsmasq
    SHELL
  end

  # PXE клиент
  config.vm.define "pxeclient" do |pxeclient|
    pxeclient.vm.box = "bento/ubuntu-22.04"
    pxeclient.vm.host_name = "pxeclient"
    pxeclient.vm.network "private_network", ip: "10.0.0.21"
    pxeclient.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
      vb.customize [
        "modifyvm", :id,
        "--nic1", "intnet",
        "--intnet1", "pxenet",
        "--nic2", "nat",
        "--boot1", "net",
        "--boot2", "none"
      ]
    end
  end
end

