Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end

  # Путь к скрипту `setup.sh` на Windows
  config.vm.provision "shell", path: "D:/vagrant/setup.sh"

  # Открываем доступ к репозиторию снаружи (опционально)
  config.vm.network "forwarded_port", guest: 80, host: 8080
end
